# -*- coding: utf-8 -*-
"""AssetManager API 클라이언트 패키지입니다.

이 패키지는 AssetManager API와 통신하여 자산 및 시장 정보를 조회하는 기능들을 제공합니다.
Pydantic 모델 형태의 구조화된 데이터를 반환하며, 통신 실패 시 AssetClientError를 발생시킵니다.
"""

from ..config import Config
from .models import (
    AssetClientError,
    AssetSummaryResponse,
    AssetRatioItem,
    AssetRatiosResponse,
    WatchlistItemPrice,
    WatchlistPricesResponse,
    MarketIndexItem,
    MarketIndicesResponse,
    MarketHolidayResponse,
    MarketHistoryItem,
    StockPriceItem,
    StockPricesResponse,
    PortfolioHoldingItem,
    PortfolioStatusResponse,
    YearlyStatItem,
    YearlyStatsResponse,
    DailyStatItem,
    DailyStatsResponse,
    TransactionItem,
    TransactionsResponse,
    SnapshotItem,
    SnapshotsResponse,
)
from .asset_api import (
    get_asset_summary,
    get_asset_ratios,
    get_portfolio_status,
    get_yearly_stats,
    get_daily_stats,
    get_snapshots,
    get_transactions,
    sync_kiwoom_transactions,
)
from .market_api import (
    get_watchlist_prices,
    get_market_indices,
    check_market_holiday,
    send_telegram_message,
    resolve_redirect_url,
    get_market_history,
    get_stock_prices,
    get_system_task_status,
)

__all__ = [
    "Config",
    "AssetClientError",
    "AssetSummaryResponse",
    "AssetRatioItem",
    "AssetRatiosResponse",
    "WatchlistItemPrice",
    "WatchlistPricesResponse",
    "MarketIndexItem",
    "MarketIndicesResponse",
    "MarketHolidayResponse",
    "MarketHistoryItem",
    "StockPriceItem",
    "StockPricesResponse",
    "PortfolioHoldingItem",
    "PortfolioStatusResponse",
    "YearlyStatItem",
    "YearlyStatsResponse",
    "DailyStatItem",
    "DailyStatsResponse",
    "TransactionItem",
    "TransactionsResponse",
    "SnapshotItem",
    "SnapshotsResponse",
    "get_asset_summary",
    "get_asset_ratios",
    "get_portfolio_status",
    "get_yearly_stats",
    "get_daily_stats",
    "get_snapshots",
    "get_transactions",
    "sync_kiwoom_transactions",
    "get_watchlist_prices",
    "get_market_indices",
    "check_market_holiday",
    "send_telegram_message",
    "resolve_redirect_url",
    "get_market_history",
    "get_stock_prices",
    "get_system_task_status",
]
